version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  # minio:
  #   build: ./minio
  #   container_name: minio
  #   restart: always
  #   environment:
  #     - MINIO_ENDPOINT='minio'
  #     - MINIO_ACCESS_KEY='dxfcgvh$^&*jbklmnkhf*(^)'
  #     - MINIO_SECRET_KEY='kjhgfy2*&^%$hbhm,nmjh2_*vc!@j0'
  #     - MINIO_BUCKET_NAME='cloudmain'
  #   expose:
  #     - 9000
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - /data