---
- name: 'deploy minio'
  hosts: 'minio_server'
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
   - ../roles/deploy_minio/vars/vars.yml
  gather_facts: true

  roles:
   - deploy_minio